export const productArray = [
  {
    id: 1,
    name: "Cheeseburger",
    img: "./burger.png",
    price: 119,
    category: "burger",
  },
  {
    id: 2,
    name: "Burger",
    img: "./burger.png",
    price: 109,
    category: "burger",
  },
  {
    id: 3,
    name: "Vegansk burger",
    img: "./burger.png",
    price: 119,
    category: "burger",
  },
  {
    id: 4,
    name: "Baconburger",
    img: "./burger.png",
    price: 129,
    category: "burger",
  },
  {
    id: 5,
    name: "Baconpølse",
    img: "./hotdog.png",
    price: 59,
    category: "hotdog",
  },
  {
    id: 6,
    name: "Ostepølse",
    img: "./hotdog.png",
    price: 59,
    category: "hotdog",
  },
  {
    id: 7,
    name: "Grillpølse",
    img: "./hotdog.png",
    price: 49,
    category: "hotdog",
  },
  {
    id: 8,
    name: "Villa",
    img: "./drinks.png",
    price: 35,
    category: "drink",
  },
  {
    id: 9,
    name: "Solo",
    img: "./drinks.png",
    price: 35,
    category: "drink",
  },
  {
    id: 10,
    name: "Mozell",
    img: "./drinks.png",
    price: 35,
    category: "drink",
  },
];
